Add colinslegacy.com instances
benbusby/farside pull request #109
Opened 2023-05-31 17:49 UTC by hendursaga

2023-06-01 00:33 UTC, benbusby requested changes
The piped and lingva instances are good to go, but the libreddit and teddit instances will need to be removed since they'll automatically get overwritten in the nightly build.

2023-06-01 00:33 UTC, benbusby commented on services-full.json
> +      "https://libreddit.colinslegacy.com"
Libreddit instances are automatically updated nightly from https://github.com/libreddit/libreddit-instances/blob/master/instances.json

2023-06-01 00:33 UTC, benbusby commented on services-full.json
> +      "https://teddit.colinslegacy.com"
Teddit instances are automatically updated from https://codeberg.org/teddit/teddit/raw/branch/main/instances.json

2023-06-04 18:30 UTC, hendursaga commented
Oh, sorry, I forgot about that! Perhaps it would be good to have a short contributing guide?

2023-06-04 21:50 UTC, hendursaga commented
(Sorry about that, I'm still trying to learn Git)

2023-06-07 17:28 UTC, benbusby approved these changes
No worries, thanks for updating!

2023-06-07 17:28 UTC, merged